<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="7905" started-at="2019-10-09T11:41:21 IST" finished-at="2019-10-09T11:41:29 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="7905" started-at="2019-10-09T11:41:21 IST" finished-at="2019-10-09T11:41:29 IST">
      <class name="com.Konakart.Pages.ValidateProductDetails">
        <test-method status="PASS" signature="startReport()[pri:0, instance:com.Konakart.Pages.ValidateProductDetails@64729b1e]" name="startReport" is-config="true" duration-ms="166" started-at="2019-10-09T11:41:21 IST" finished-at="2019-10-09T11:41:21 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startReport -->
        <test-method status="PASS" signature="setup()[pri:0, instance:com.Konakart.Pages.ValidateProductDetails@64729b1e]" name="setup" is-config="true" duration-ms="7876" started-at="2019-10-09T11:41:21 IST" finished-at="2019-10-09T11:41:29 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="validateProductDetail(java.lang.String, java.lang.String)[pri:0, instance:com.Konakart.Pages.ValidateProductDetails@64729b1e]" name="validateProductDetail" duration-ms="0" started-at="2019-10-09T11:41:29 IST" data-provider="pro2descriptionandspecification" finished-at="2019-10-09T11:41:29 IST">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
Method public static void com.Konakart.Pages.ValidateProductDetails.validateProductDetail(java.lang.String,java.lang.String) throws java.lang.Exception requires a @DataProvider named : pro2descriptionandspecification]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
Method public static void com.Konakart.Pages.ValidateProductDetails.validateProductDetail(java.lang.String,java.lang.String) throws java.lang.Exception requires a @DataProvider named : pro2descriptionandspecification
at org.testng.internal.Parameters.findDataProvider(Parameters.java:580)
at org.testng.internal.Parameters.handleParameters(Parameters.java:795)
at org.testng.internal.Parameters.handleParameters(Parameters.java:762)
at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:60)
at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:39)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:771)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateProductDetail -->
        <test-method status="FAIL" signature="validateProductDetails(java.lang.String, java.lang.String)[pri:0, instance:com.Konakart.Pages.ValidateProductDetails@64729b1e]" name="validateProductDetails" duration-ms="0" started-at="2019-10-09T11:41:29 IST" data-provider="pro1descriptionandspecifications" finished-at="2019-10-09T11:41:29 IST">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
Method public static void com.Konakart.Pages.ValidateProductDetails.validateProductDetails(java.lang.String,java.lang.String) throws java.lang.Exception requires a @DataProvider named : pro1descriptionandspecifications]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
Method public static void com.Konakart.Pages.ValidateProductDetails.validateProductDetails(java.lang.String,java.lang.String) throws java.lang.Exception requires a @DataProvider named : pro1descriptionandspecifications
at org.testng.internal.Parameters.findDataProvider(Parameters.java:580)
at org.testng.internal.Parameters.handleParameters(Parameters.java:795)
at org.testng.internal.Parameters.handleParameters(Parameters.java:762)
at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:60)
at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:39)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:771)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateProductDetails -->
        <test-method status="PASS" signature="endReport()[pri:0, instance:com.Konakart.Pages.ValidateProductDetails@64729b1e]" name="endReport" is-config="true" duration-ms="605" started-at="2019-10-09T11:41:29 IST" finished-at="2019-10-09T11:41:29 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endReport -->
      </class> <!-- com.Konakart.Pages.ValidateProductDetails -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
